= Pivotal Big Data Roadshow  - Hands-on Technical Workshop

So far this consists of:

* this README
* link:labs/springxd[Data Streaming with Spring XD, GemFire and PHD]
* link:labs/phd-hawq[PHD and Hawq Overview Lab]
* link:labs/gemfire[GemFire Overview Lab (optional)]  
* link:labs/realtime-stream-demo[Real Time Stream Demo using Pivotal Stack]

== Environment

The labs are built for running on any environment with the right products installed.  
In order to make it simpler, we've created the Amazon AMI to launch instances quickly. There is no .pem requirement to login in to the EC2 instance once AMI is launced.

Log in to your AWS account and search for AMI ID - ami-b4a7a9e6 (available in Singapore region). 

- Launch it and make sure you choose m4.xlarge (16GB) instance size. Note: You could also try with t2.large (8GB) - we tried it and it works, however you may experience slowness.

- Auto assign a public IP address

- Add 25 GB SSD storage 

- Keep all traffic open on all ports in your security group settings 

- No need to choose a key pair.

Once launched, you could ssh to machine using gpadmin/changeme credentials.
